spring:
  datasource:
    url: jdbc:h2:mem:user_db
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

  liquibase:
    change-log: classpath:liquibase/db.changelog-master.yaml

logging:
  level:
    ru.bagrov.user.rest.api.app: DEBUG
